DELIMITER $$
CREATE FUNCTION CHROM(
	inp BIGINT
) 
RETURNS CHAR(2)
DETERMINISTIC
BEGIN
DECLARE str CHAR(2);
DECLARE cn INTEGER;
SET cn = (inp >> 58);
CASE
WHEN cn < 23 THEN SET str = CONVERT(cn,char);
WHEN cn = 23 THEN SET str = 'X';
WHEN cn = 24 THEN SET str = 'Y';
WHEN cn = 25 THEN SET str = 'MT';
END CASE;
RETURN str;
END$$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION POS(
	inp BIGINT
) 
RETURNS INT
DETERMINISTIC
BEGIN
	RETURN ((inp >> 30) % 268435456) - ((((inp >> 24) % 64) = 0) OR (((inp >> 18) % 64) = 0));
END$$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION REF(
inp BIGINT
)
RETURNS VARCHAR(255) 
DETERMINISTIC
BEGIN
DECLARE o VARCHAR(255);
SELECT REF INTO o FROM VARIANT WHERE RSVR_ID = inp;
RETURN o;
END$$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION ALT(
inp BIGINT
)
RETURNS VARCHAR(255)
DETERMINISTIC
BEGIN
DECLARE v BIGINT;
DECLARE r INTEGER;
DECLARE x INTEGER;
DECLARE refl INTEGER;
DECLARE altl INTEGER;
DECLARE str VARCHAR(255);
SET v = inp % (1 << 18);
SET refl = (inp >> 24) % 64;
SET altl = (inp >> 18) % 64;
SET str = '';
IF ((refl = 0) OR (altl = 0)) THEN
SET str = SUBSTR(REF(inp),1,1);
END IF;
SET x = 0;
loop_label:  LOOP
IF x >= altl THEN
LEAVE  loop_label;
END  IF;
SET x = x + 1;
SET r = (v % 4);
CASE 
WHEN x BETWEEN 6 AND (altl-4) THEN SET str = CONCAT(str, '?');
WHEN r = 0 THEN SET str = CONCAT(str,'A');
WHEN r = 1 THEN SET str = CONCAT(str,'C');
WHEN r = 2 THEN SET str = CONCAT(str,'G');
ELSE SET str = CONCAT(str,'T');
END CASE;
SET v = v DIV 4;
ITERATE  loop_label;
END LOOP;
RETURN str;
END$$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION CONSEQUENCES(
inp BIGINT
)
RETURNS TEXT
DETERMINISTIC
BEGIN
DECLARE v BIGINT;
DECLARE r INTEGER;
DECLARE t INTEGER;
DECLARE o TEXT;
DECLARE c VARCHAR(255);
SET v = inp;
SET r = 0;
SET t = 0;
SET o = '';
loop_label:  LOOP
IF v = 0 THEN
LEAVE loop_label;
END  IF;
SELECT NAME INTO c FROM CONSEQUENCES_LIST WHERE BIT = r;
SET r = r + 1;
IF v % 2 = 1 THEN
IF t > 0 THEN
SET o = CONCAT(c, ', ', o);
ELSE 
SET o = c;
END IF;
SET t = t + 1;
END IF;
SET v = v DIV 2;
ITERATE  loop_label;
END LOOP;
RETURN o;
END$$
DELIMITER ;

DELIMITER $$
CREATE FUNCTION CSQ_NAME_TO_ID(
	csq_name VARCHAR(255)
) 
RETURNS BIGINT
DETERMINISTIC
BEGIN
DECLARE cn INTEGER;
SELECT BIT INTO cn FROM CONSEQUENCES_LIST WHERE NAME = csq_name;
RETURN (1 << cn);
END$$
DELIMITER ;
